### PR TITLE
Entries search specs

### PR DESCRIPTION
**Pull request by shhavel**
#2 
Added model and controller tests for full-text search

### CODE REVIEW

**Review by povodok — APPROVED** [review]

**Review by mahasamatman — CHANGES_REQUESTED** [review]
screen shot 2017-09-13 at 10 53 50

Hey, there are few failing specs:)

**Comment by shhavel** [comment]
@mahasamatman I have no failed tests locally and there are no on CI as well.
Can you please provide errors description?

**Comment by mahasamatman** [comment]
@shhavel, sure. From time to time there are. Looks like database not properly populated or cleaned hence tests success depends on order in which they ran.
screen shot 2017-09-13 at 11 44 41

**Comment by mahasamatman** [comment]
It seems like locale issue, sorry, not a database.

**Comment by shhavel** [comment]
@mahasamatman You are right, there was an issue with tests. Now I set locale explicitly in controller and request tests, so it should be fixed. Thanks

**Review by mahasamatman — APPROVED** [review]

**Pull request merged**
